CREATE TABLE IF NOT EXISTS bpjs_referral (
  patient_nik VARCHAR(32) PRIMARY KEY REFERENCES pasien(nik)
    ON UPDATE CASCADE ON DELETE CASCADE,
  poli_id INTEGER NOT NULL REFERENCES tbpoli("IdPoli")
    ON UPDATE CASCADE ON DELETE RESTRICT,
  doctor_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);
